### ISSUE TITLE
DTD file completion not detected properly

### ISSUE THREAD

**Issue by ejgutierrez74** [redhat-developer/vscode-xml#945]
I have one file called ( of course in the same directory as xml file) a DTD file called bautistamonicaoriginal.dtd.....In vscode it detects lots of files...except the one i need....

![imagen](https://github.com/redhat-developer/vscode-xml/assets/11474846/8e3a6e0a-316e-418d-84ec-6d844139d719)

At the same time you wrote the file name, it appear lots of files....

![imagen](https://github.com/redhat-developer/vscode-xml/assets/11474846/8d1c67ef-8e03-4e6b-b13e-7c24fa85e256)

![imagen](https://github.com/redhat-developer/vscode-xml/assets/11474846/9c73192e-4c6f-431e-b416-aad4ea782b49)

But no one even began with b or ba or bau or baut...and so on....the files which name is helping are far similar to the one i seek

**Comment by fbricon** [comment]
I can reproduce this weird behavior. When completing on `<!DOCTYPE foo SYSTEM "|">`, it seems it's listing the contents of the parent directory instead of the current one.

**Comment by angelozerr** [comment]
@ejgutierrez74 if I remember you need to write `./` before, but I agree it is an annoying issue.

**Comment by ejgutierrez74** [comment]
> @ejgutierrez74 if I remember you need to write `./` before, but I agree it is an annoying issue.

No  i dont, im on linux system...in xml copy editor and other like netbeans works ok. I remind that both files are in same directory. I put an Example of changing directory without ./

![imagen](https://github.com/redhat-developer/vscode-xml/assets/11474846/e36e4869-afa8-4697-a39b-b95fc9eb6553)

**Comment by fbricon** [comment]
The issue is caused by https://github.com/eclipse/lemminx/pull/1293/files

The current file completion has some outstanding issues:
- it lists files from the parent directory, when requesting completion for something that doesn't start with a files separator
- it prefixes all results with a /, even when requesting ./something
- applying completion appends the text to the existing value. eg. if you complete "|./foo.dtd" and select the existing "foo.dtd", the result will be ".foo.dtd./foo.dtd"

**Comment by ejgutierrez74** [comment]
> The issue is caused by https://github.com/eclipse/lemminx/pull/1293/files
> 
> The current file completion has some outstanding issues:
> 
>     * it lists files from the parent directory, when requesting completion for something that doesn't start with a files separator
> 
>     * it prefixes all results with a /, even when requesting ./something
> 
>     * applying completion appends the text to the existing value. eg. if you complete "|./foo.dtd" and select the existing "foo.dtd", the result will be "foo.dtd./foo.dtd"

Its then solved the error ? I see amerged code, dont know if its fixed in new release or nightly or prerelease code....Thanks

**Comment by angelozerr** [comment]
As soon as the issue is not closed it means that it is not fixed. 

We need to create a PR. @fbricon have you the intention to fix it?

**Comment by ejgutierrez74** [comment]
@fbricon ???

**Comment by fbricon** [comment]
Sorry I'm busy with other tasks so don't expect me to fix it any time soon. 

The problem was introduced in https://github.com/eclipse/lemminx/pull/1293. @ejgutierrez74 feel free to open a PR to fix it.

**Comment by angelozerr** [comment]
Thanks @fbricon for your answer.

I think this file completion must be revisited . I will try to do that to integrate to the next release but I cannot promise you @ejgutierrez74 that I will be able to do that.

**Comment by ejgutierrez74** [comment]
Dont promise me, promise to fix it  to my students @angelozerr  ;)

**Comment by angelozerr** [comment]
@ejgutierrez74 here a demo with my current work:

![DTDFileCompletion](https://github.com/redhat-developer/vscode-xml/assets/1932211/f2fd9cc1-a833-408e-aa75-2a0bae0193af)

**Comment by ejgutierrez74** [comment]
Seems great
Thank you for your effort

**Comment by angelozerr** [comment]
Fixed with https://github.com/eclipse/lemminx/pull/1604

@ejgutierrez74 the DTD file completion should work now. Please install the pre-release (I think it will be available tomorrow) and give us feedback if it is working correctly for you. Thanks!

**Comment by ejgutierrez74** [comment]
My tests three or four files, in VsCode in Ubuntu 22.04 seems that work great....
Any ETA when avalaible to general public ?

Thanks for your work.
Didnt test it because we havent arrived to Schema....but should work and detect XSD files....no ??

**Comment by angelozerr** [comment]
> seems that work great.

Nice!

> Any ETA when avalaible to general public ?

We will try to create a release next week if we have time.

> Thanks for your work.

You are welcome.

> but should work and detect XSD files....no ??

Yes it should work.

**Comment by ejgutierrez74** [comment]
Any news ??
Happy new year
Seems no new release has been published....

**Comment by angelozerr** [comment]
Happy new year @ejgutierrez74 

We need to find time to create this release, since we are very busy with other projects.
